# Generated by Django 3.1.8 on 2021-06-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='revision_url',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
