# Generated by Django 3.1.8 on 2021-06-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versioning', '0002_revision_revision_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='index',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
